export const projects = [
  {
    cat: "Security",
    title: "Cowrie SSH Honeypot + Wazuh SIEM",
    why: "I needed to understand how attackers behave in the wild — not just read about it. Setting up a real honeypot and shipping its logs to a SIEM gave me hands-on visibility into brute-force patterns and MITRE ATT&CK techniques.",
    what: "Deployed a Cowrie SSH honeypot on Raspberry Pi, silently redirected port 22 to 2223 via iptables, and integrated Wazuh Agent to ship JSON logs to a Windows Wazuh Manager for real-time MITRE ATT&CK correlation.",
    learned: "How attackers enumerate, the value of deception networks, writing custom Wazuh XML rules, and how log pipelines work from edge device to SIEM dashboard.",
    tech: ["Wazuh", "Cowrie", "iptables", "Docker", "Raspberry Pi", "XML Rules"],
    link: "https://github.com/blup-blup-spec/honeypot",
  },
  {
    cat: "Security",
    title: "RECON OPERATOR v3",
    why: "Manual recon is slow and error-prone. I wanted a GUI-driven tool that automates a full 6-phase methodology so a tester can focus on analysis, not copy-pasting commands.",
    what: "Built a PyQt6 GUI automating ping sweeps, TTL-based OS fingerprinting, banner grabbing with CVE matching, WHOIS lookups, and stealth timing profiles T0–T4.",
    learned: "Network reconnaissance methodology, Python-Nmap API internals, how CVE databases map to service banners, and designing intuitive security tooling UIs.",
    tech: ["PyQt6", "Python-Nmap", "DNSutils", "WHOIS", "Python"],
    link: "https://github.com/blup-blup-spec/Recon",
  },
  {
    cat: "Security",
    title: "Linux Firewall Security Hardening",
    why: "Running Kali tools without proper isolation is dangerous. I wanted to create a hardened, containerized environment so security operations happen inside a locked-down sandbox.",
    what: "Built a Docker-based Kali environment with custom Seccomp profiles for kernel syscall filtering, automated iptables/UFW rule sets, and privilege-dropping entrypoints.",
    learned: "Seccomp syscall whitelisting, how Docker namespaces isolate processes, and production-grade firewall rule design for security labs.",
    tech: ["Docker", "Seccomp", "Iptables", "UFW", "Kali Linux", "Python"],
    link: "https://github.com/blup-blup-spec/Linux-Firewall-Security-Hardening",
  },
  {
    cat: "AI",
    title: "SEIZURE – Epilepsy Prediction",
    why: "Epileptic seizures are life-threatening and often unpredictable. I wanted to build something that could give patients advance warning using EEG signals and edge AI.",
    what: "Trained a 1D-MobileNetV2 CNN on CHB-MIT multi-channel EEG data, converted to Float16 TFLite, and deployed on Raspberry Pi for real-time pre-ictal state detection.",
    learned: "EEG signal preprocessing with MNE-Python, CNN architectures for 1D time-series, TFLite quantization tradeoffs, and the ethics of medical AI.",
    tech: ["MobileNetV2", "TFLite", "Keras", "MNE-Python", "EEG"],
    link: "https://github.com/blup-blup-spec/SEIZURE",
  },
  {
    cat: "IoT",
    title: "Ophidian – Snake Detection System",
    why: "Wildlife-prone areas around KIIT campus had snake sightings. I wanted a low-cost, always-on camera system that could distinguish venomous from non-venomous snakes.",
    what: "Fine-tuned YOLOv8n on a custom dataset, quantized to INT8 TFLite, deployed on Raspberry Pi 4 with OpenCV achieving 15–22 FPS real-time classification.",
    learned: "Edge model optimization (INT8 quantization), transfer learning for wildlife datasets, UART servo integration, and real-time CV pipeline design.",
    tech: ["YOLOv8", "TFLite INT8", "OpenCV", "Raspberry Pi 4", "Python"],
    link: "https://github.com/blup-blup-spec/ophidian",
  },
  {
    cat: "IoT",
    title: "HealthGuard – Smart Arm Band",
    why: "Remote health monitoring for elderly people is expensive. I wanted to build a wearable that costs very little but streams real vitals to family and doctors continuously.",
    what: "ESP32 wearable monitoring heart rate and SPO2, syncing via Firebase to a Flutter dashboard with real-time graphs and alert thresholds.",
    learned: "BLE sensor integration, Firebase Realtime Database streams, Flutter state management, and battery-efficient embedded firmware design.",
    tech: ["ESP32", "Flutter", "Firebase", "C++", "SPO2 Sensors"],
    link: "https://github.com/blup-blup-spec/healthgaurd",
  },
  {
    cat: "Robotics",
    title: "LL1.0 – 12-DOF Quadruped Robot",
    why: "I wanted to understand legged locomotion from scratch — not simulations, but actual hardware that walks, turns, and responds to voice commands in real time.",
    what: "Built a 12-servo quadruped using Inverse Kinematics for gait control, WebSocket remote control, OpenCV target tracking, and LoRa for long-range comms.",
    learned: "IK gait mathematics, real-time servo coordination, WebSocket communication, computer vision on embedded boards, and system integration across multiple hardware layers.",
    tech: ["C++", "IK Gait", "WebSocket", "OpenCV", "LoRa", "Voice Engine"],
    link: "https://github.com/blup-blup-spec/LL1.0",
  },
  {
    cat: "Networking",
    title: "Cisco Enterprise Network Design",
    why: "Understanding enterprise networking at the design level — not just CLI commands — is essential for any security engineer. I built a full campus network to learn this deeply.",
    what: "Designed a multi-building campus network in Packet Tracer with VLAN segmentation, Inter-VLAN routing, DHCP automation, ACLs, and SSH remote management.",
    learned: "Layer 3 switching, VLAN design principles, ACL rule ordering, DHCP scope management, and how large-scale enterprise networks are logically structured.",
    tech: ["Cisco Packet Tracer", "VLANs", "DHCP", "ACLs", "Inter-VLAN"],
    link: "https://github.com/blup-blup-spec/cisco-packet-tracer",
  },
  {
    cat: "AI",
    title: "Medico AI – Medical Study Assistant",
    why: "Medical textbooks are dense and hard to visualize. I wanted an AI-powered tool that translates drug mechanisms and diagnostics into interactive visual flowcharts.",
    what: "Flutter app integrated with Llama 3 via NVIDIA NIM, rendering complex medical queries as zoomable, interactive flowcharts stored in Firestore.",
    learned: "LLM prompt engineering for structured output, NVIDIA NIM API, dynamic Flutter widget trees for flowcharts, and medical ontology.",
    tech: ["Flutter", "NVIDIA NIM", "Llama 3", "Groq", "Firestore"],
    link: "https://github.com/blup-blup-spec/appmap",
  },
  {
    cat: "Software",
    title: "TutorGuide – Management System",
    why: "My tutoring center needed a unified platform — no scattered WhatsApp messages for notes and no honor-system MCQ tests that could be cheated.",
    what: "Cross-platform Flutter app with RBAC (teacher/student roles), YouTube deep-link lecture integration, anti-cheat timed MCQs, and real-time dashboards via Firestore.",
    learned: "Firebase Auth role-based access patterns, Firestore security rules, Flutter navigation architecture, and UX design for educational platforms.",
    tech: ["Flutter", "Firebase Auth", "Firestore", "Dart"],
    link: "https://github.com/blup-blup-spec/tution_app",
  },
  {
    cat: "DSP",
    title: "Audio Sculptor – MATLAB DSP GUI",
    why: "I wanted to go beyond theory and actually implement DSP algorithms — pitch shifting, filtering, voice conversion — with a real UI where you hear the output instantly.",
    what: "MATLAB GUI application (ProjectGUI.m + .fig) featuring real-time audio recording, pitch control, speed manipulation, echo/reverb, high-pass filtering, and a male-to-female voice converter using STFT-based phase vocoder with cepstral formant preservation.",
    learned: "Short-Time Fourier Transform, Phase Vocoder theory, cepstral analysis for formant separation, source-filter speech model, and building interactive GUIs in MATLAB App Designer.",
    tech: ["MATLAB", "STFT", "Phase Vocoder", "Cepstral Analysis", "DSP", "GUI"],
    link: "https://github.com/blup-blup-spec/audio-sculptor",
  },
  {
    cat: "Electronics",
    title: "FM Receiver – STM32 & TEA5767",
    why: "I wanted to understand how digital radio tuning actually works at the hardware level — replacing analog LC circuits with precise PLL-based digital control.",
    what: "STM32F446RE microcontroller communicating with TEA5767 FM radio IC via I2C, displaying the tuned frequency on SSD1306 OLED. Raspberry Pi served as a local FM transmitter for testing.",
    learned: "I2C protocol master/slave addressing, PLL word calculation for frequency synthesis, OLED display buffer management, and how FM demodulation works in integrated circuits.",
    tech: ["STM32F446RE", "TEA5767", "I2C", "SSD1306 OLED", "C", "HAL Libraries"],
    link: "https://github.com/blup-blup-spec/FM",
  },
  {
    cat: "IoT",
    title: "Gesture Control – Contactless Motor System",
    why: "Physical switches are limiting for motor control applications. I wanted a hands-free system that uses Computer Vision to detect hand gestures and translate them into servo motor commands.",
    what: "Built a contactless motor control system using MediaPipe hand tracking (21 landmarks) and OpenCV. 6 distinct gestures control 3 independent servo motors. Face Recognition (LBPH) secures access. Flask web dashboard streams live camera feed and motor status.",
    learned: "MediaPipe hand landmark geometry, LBPH face recognition, Flask MJPEG streaming, RPi.GPIO PWM control, and building production-grade edge CV pipelines.",
    tech: ["MediaPipe", "OpenCV", "Flask", "Raspberry Pi", "RPi.GPIO", "Python"],
    link: "https://github.com/blup-blup-spec/gesture",
  },
];

export const certificates = [
  { title: "Linux", issuer: "Certificate", year: "2026", img: "/certificate/linux.png" },
  { title: "Vois Foundation Program", issuer: "Vois", year: "2025", img: "/certificate/vois.png" },
  { title: "Intro to Cybersecurity", issuer: "Cisco", year: "2026", img: "/certificate/into to cybersec by cisco.png" },
  { title: "Networking Basics", issuer: "Cisco", year: "2026", img: "/certificate/NETWROKING_BASIC BY cisco.png" },
  { title: "Cybersecurity Analyst", issuer: "Tata / Forage", year: "2025", img: "/certificate/Cybersecurity Analyst Job Simulation by tata forage.png" },
];

export const achievements = [
  { title: "Kreativity 3.0 – 3rd Place", desc: "Awarded 3rd place for the LL1.0 Quadruped Robot. Live-demoed IK gait locomotion and voice-command control in front of the judging panel.", img: "/achieve/kreativity3.0.png" },
  { title: "Pragati 2024", desc: "Led my team as Tech Lead at Jadavpur University to build an Autonomous Snake Detection System using YOLO. Selected among the Top 8 teams at the Pragati Hackathon.", img: "/achieve/Pragati.png" },
  { title: "Electrical Expo — 2nd Place", desc: "Awarded 2nd Place for the IoT Smart Wheelchair. Built with Dual ESP32 via ESP-NOW (<10ms latency), a Firebase web dashboard for live health monitoring, and an MPU6050 IMU for fall detection.", img: "/achieve/electrical_expo.png" },
];

export const PROJECT_CATS = ["All", "Security", "AI", "IoT", "Networking", "DSP", "Electronics", "Robotics", "Software"];
